common/models/ExamPreparation.php
<?php

namespace common\models;

use backend\models\User;
use services\exam\ExamPreparationService;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "exam_preparation".
 *
 * @property int $id
 * @property string $title
 * @property string $sub_title
 * @property string $date_start
 * @property string $date_completion
 * @property string $publish
 * @property string $empty_date
 * @property string $register
 * @property string $status
 * @property string $sub_status
 * @property string $code
 * @property int $lecturer
 * @property int $responsible_id
 * @property int $template_exam_id
 * @property string $create_at
 * @property string $update_at
 *
 * @property WeeklyExamPreparation $weekly
 */
class ExamPreparation extends ActiveRecord
{
    const PUBLISH_OPEN = 'yes';
    const PUBLISH_CLOSE = 'no';

    const REGISTER_OPEN = 'yes';
    const REGISTER_CLOSE = 'no';

    const KNOW_DATE = 'yes';
    const NOT_KNOW_DATE = 'no';

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'exam_preparation';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'code', 'responsible_id'], 'required'],
            [['status', 'sub_status'], 'required', 'when' => function ($model) {
                return $model->empty_date === static::NOT_KNOW_DATE;
            }],
            [
                ['date_start'], 'required', 'when' => function ($model) {
                return $model->empty_date === static::KNOW_DATE;
            }, 'whenClient' => "function (attribute, value) {
                    return $('#empty_date').val() === 'yes';
                }"
            ],
            [['date_start', 'date_completion', 'create_at', 'update_at'], 'safe'],
            [['responsible_id', 'template_exam_id'], 'integer'],
            [['title', 'sub_title', 'publish', 'code', 'lecturer', 'status', 'sub_status', 'register', 'empty_date'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id'               => 'Индетификатор',
            'title'            => 'Название на странице курса',
            'sub_title'        => 'Короткое название',
            'date_start'       => 'Дата старта',
            'date_completion'  => 'Дата окончания',
            'publish'          => 'Публикация на главной странице',
            'empty_date'       => 'Известна дата?',
            'status'           => 'Статус курса для страницы курса',
            'sub_status'       => 'Статус курса для главной страницы',
            'register'         => 'Открыта ли регистрация на курс',
            'code'             => 'Символьный код',
            'lecturer'         => 'Куратор',
            'responsible_id'   => 'Координатор',
            'template_exam_id' => 'Шаблон',
            'create_at'        => 'Создано',
            'update_at'        => 'Обновлено',
        ];
    }

    public function isPublish()
    {
        return $this->publish === static::PUBLISH_OPEN;
    }

    public function getWeeklyExamPreparation()
    {
        /** @var WeeklyExamPreparation $weekly */
        $weekly = ArrayHelper::getValue($this, 'weeklyExam');
        if ($weekly === null) {
            return [];
        }

        return $weekly->getFullWeekExamPreparation();
    }

    public function getExamPreparationDateRange()
    {
        return \Yii::t('app', 'с {from} по {to}', [
            'from' => \Yii::$app->formatter->asDate($this->date_start),
            'to'   => \Yii::$app->formatter->asDate($this->date_completion),
        ]);
    }

    public function getWeeklyExamPreparationForPage()
    {
        $records = $this->getWeeklyExamPreparation();
        if (count($records) === 1) {
            return \Yii::t('app', 'по {day} в {time}', [
                'day'  => mb_strtolower($records[0]['label_week']),
                'time' => $records[0]['time'],
            ]);
        }

        if (count($records) === 2) {
            return \Yii::t('app', 'по {day} и {end_day} в {time}', [
                'day'     => mb_strtolower($records[0]['label_week']),
                'end_day' => mb_strtolower($records[1]['label_week']),
                'time'    => $records[0]['time'],
            ]);
        }

        $last = array_pop($records);
        $days = [];
        foreach ($records as $record) {
            $days[] = mb_strtolower($record['label_week']);
        }

        return \Yii::t('app', 'по {all_day} и {end_day} в {time}', [
            'all_day' => implode(', ', $days),
            'end_day' => mb_strtolower($last['label_week']),
            'time'    => $last['time'],
        ]);
    }

    public function getResponsible()
    {
        return $this->hasOne(User::class, ['id' => 'responsible_id']);
    }

    public function getTemplateExam()
    {
        return $this->hasOne(TemplateExamPreparation::class, ['id' => 'template_exam_id']);
    }

    public function getWeeklyExam()
    {
        return $this->hasOne(WeeklyExamPreparation::class, ['exam_preparation_id' => 'id']);
    }

    public function getActiveStatusLabel()
    {
        return ExamPreparationService::instance()->statusLabelForDates([$this->id]);
    }

    public function isFinished()
    {
        if ($this->date_completion === null) {
            return false;
        }
        $now = new \DateTime();
        $end = new \DateTime($this->date_completion);
        return $now > $end;
    }

    public function canRegister()
    {
        $start = (new \DateTime($this->date_start))->add(new \DateInterval('P7D'));
        $now = new \DateTime();

        if ($this->empty_date !== static::NOT_KNOW_DATE) {
            return $now < $start;
        }
        return $this->register === ExamPreparation::REGISTER_OPEN;
    }
}

backend/controllers/ExamPreparationController.php
<?php

namespace backend\controllers;

use backend\forms\exam\Create;
use backend\forms\exam\Search;
use backend\forms\recordschoolchild\CreateRecordSchoolchild;
use backend\forms\recordschoolchild\SearchRecordSchoolchild;
use backend\forms\schoolchild\CreateSchoolchild;
use backend\forms\template_exam\CreateTemplate;
use common\models\TemplateExamPreparation;
use services\exam\ExamPreparationService;
use services\exam\RecordSchoolchildService;
use services\exam\TemplateExamPreparationService;
use services\profile\SchoolchildService;
use yii\base\Module;
use yii\filters\AccessControl;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\Response;

/**
 * Exam Preparation controller
 */
class ExamPreparationController extends Controller
{

    /** @var ExamPreparationService */
    private $exam_preparation;

    /** @var TemplateExamPreparationService */
    private $template_exam;

    public function __construct(string $id, Module $module, ExamPreparationService $exam_preparation, array $config = [])
    {
        $this->exam_preparation = $exam_preparation;
        parent::__construct($id, $module, $config);
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    ['allow' => true, 'roles' => ['@']]
                ],
            ],
        ];
    }

    public function actionMain()
    {
        $query_template = TemplateExamPreparation::find()->one();

        if ($query_template == null) {
            $template = [
                'model' => new CreateTemplate(),
                'view'  => 'template/_create'
            ];
        } else {
            $template = [
                'model' => TemplateExamPreparationService::instance()->findForForm($query_template->id),
                'view'  => 'template/_update'
            ];
        }

        $search = new Search();
        $provider = $search->search();

        $request = \Yii::$app->request;
        $schoolchild_form = new CreateSchoolchild();

        if ($schoolchild_form->load($request->post()) && $schoolchild_form->validate()) {
            (new SchoolchildService())->insert($schoolchild_form);
            \Yii::$app->session->setFlash('success', 'Новый школьник был успешно создан');
            return $this->redirect(['exam-preparation/main']);
        }

        $record_form = new CreateRecordSchoolchild();
        if ($record_form->load($request->post()) && $record_form->validate()) {
            (new RecordSchoolchildService())->create($record_form);
            \Yii::$app->session->setFlash('success', 'Новая запись на курс была успешно создана');
            return $this->redirect(['exam-preparation/main']);
        }

        $record_filter = new SearchRecordSchoolchild();
        $record_provider = $record_filter->search();

        return $this->render('main', [
            'template'         => $template,
            'provider'         => $provider,
            'search'           => $search,
            'record_form'      => $record_form,
            'schoolchild_form' => $schoolchild_form,
            'record_filter'    => $record_filter,
            'record_provider'  => $record_provider,
        ]);
    }

    public function actionCreate()
    {
        $exam_preparation = new Create();
        if ($exam_preparation->load(\Yii::$app->request->post()) && $exam_preparation->validate()) {
            $this->exam_preparation->insert($exam_preparation);
            return $this->redirect(['exam-preparation/main']);
        }

        $template = TemplateExamPreparation::find()->one();
        return $this->render('create', [
            'exam_preparation' => $exam_preparation,
            'template_id'      => $template->id
        ]);
    }

    public function actionUpdate(int $id)
    {
        $request = \Yii::$app->request;
        $exam_preparation = $this->exam_preparation->findForForm($id);

        \Yii::$app->response->format = Response::FORMAT_JSON;

        if ($request->post()) {
            if ($exam_preparation->load($request->post()) && $exam_preparation->validate()) {
                $this->exam_preparation->insert($exam_preparation);
                return [
                    'msg' => true
                ];
            } else {
                return [
                    'msg'    => false,
                    'errors' => $exam_preparation->errors
                ];
            }
        } else {
            \Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'icon'      => null,
                'sub_title' => null,
                'title'     => $exam_preparation->title,
                'content'   => $this->renderAjax('update', [
                    'exam_preparation' => $exam_preparation,
                ])
            ];
        }
    }

    public function actionPublish(int $id)
    {
        $request = \Yii::$app->request;
        if ($request->getIsAjax() === false) {
            throw new BadRequestHttpException();
        }

        $checked = $request->post('checked') === 'true';
        $this->exam_preparation->publish($id, $checked);
    }

}

frontend/controllers/ExamPreparationController.php
<?php

namespace frontend\controllers;

use common\models\ExamPreparation;
use frontend\forms\CourseRegisterExamPreparation;
use services\exam\RecordSchoolchildService;
use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * Site controller
 */
class ExamPreparationController extends Controller
{
    public $layout = '//education';

    public function actionIndex(string $code)
    {
        $exam_preparation = ExamPreparation::find()
            ->where([
                'and',
                ['=', 'code', $code],
                ['=', 'publish', ExamPreparation::PUBLISH_OPEN]
            ])
            ->one();
        if ($exam_preparation === null) {
            throw new NotFoundHttpException();
        }

        return $this->render('index', ['exam_preparation' => $exam_preparation]);
    }

    public function actionRegister(int $id)
    {
        $register = new CourseRegisterExamPreparation();
        $register->exam_preparation_id = $id;
        $send = false;

        if ($register->load(Yii::$app->request->post()) && $register->validate()) {
            RecordSchoolchildService::instance()->createFromFrontend($register);
            $send = true;
        }

        return $this->renderAjax('register', [
            'register'         => $register,
            'send'             => $send,
            'exam_preparation' => $register->getExamPreparation(),
        ]);
    }
}

frontend/views/exam-preparation/index.php
<?php

use backend\models\User;
use common\models\ExamPreparation;
use common\models\Files;
use common\models\TemplateExamPreparation;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;

/**
 * @var $this View
 * @var $exam_preparation ExamPreparation
 * @var $template TemplateExamPreparation
 */

$this->title = 'Академия разработки MediaSoft: ' . $exam_preparation->title;
$template = $exam_preparation->getTemplateExam()->one();

?>
<span id="arrow_back" class="toggle-arrow">
    <?php echo Html::a('<i class="arrow-svg"></i>', Url::previous()); ?>
</span>

<section class="education_title">
    <div class="container">
        <div class="logo">
            <a href="/">
                <img src="/images/logo_academy_rgb.png" alt="">
            </a>
        </div>
        <div class="description">
            <div class="name_course"><?= $exam_preparation->title; ?></div>
            <div class="price_course">Обучение бесплатное</div>
            <div class="date_begin_course"><?= $exam_preparation->empty_date === ExamPreparation::NOT_KNOW_DATE ? $exam_preparation->status : $exam_preparation->getActiveStatusLabel(); ?></div>
            <?php if ($exam_preparation->isFinished() === false): ?>
                <?php if (ArrayHelper::getValue($exam_preparation, 'empty_date') !== ExamPreparation::NOT_KNOW_DATE): ?>
                    <div class="schedule_course">Занятия проходят <?= $exam_preparation->getWeeklyExamPreparationForPage() ?></div>
                <?php endif; ?>
                <?php if ($exam_preparation->canRegister()): ?>
                    <div class="action_course">
                        <?php
                        echo Html::a('Зарегистрироваться', 'javascript: void(0)', ['data' => ['popup' => 'register', 'request' => Url::to(['exam-preparation/register', 'id' => $exam_preparation->id])]]);
                        ?>
                    </div>
                <?php endif; ?>
            <?php endif; ?>
            <div class="address_course"><b>MediaSoft</b> / Ульяновск, ул. К.Маркса,13А, корп.3 <span>(ТЦ Амарант, 3 этаж) /</span>
            </div>
        </div>
    </div>
</section>

<section class="education_about">
    <div class="about_wrapper flex">
        <div class="light_section">
            <div class="wrapper_section">
                <div class="title_section">Для кого</div>
                <div class="content_section_wrapper"><?= $template->left_description ?></div>
            </div>
        </div>
        <div class="dark_section">
            <div class="wrapper_section">
                <div class="title_section">Что дает курс</div>
                <div class="content_section_wrapper"><?= $template->right_description ?></div>
            </div>
        </div>
    </div>
</section>
<section class="education_program">
    <div class="container">
        <div class="title_section">О курсе</div>
        <div class="wrapper_content">
            <?= $template->about_course ?>
        </div>
    </div>
</section>
<section class="education_program">
    <div class="container">
        <div class="title_section">Программа</div>
        <div class="wrapper_content">
            <?= $template->program ?>
        </div>
    </div>
</section>

<section class="education_record">
    <div class="record_wrapper flex">
        <div class="light_section">
            <div class="wrapper_section">
                <div class="title_section">Информация</div>
                <div class="content_section_wrapper">
                    <ul>
                        <li><b>Участие бесплатно</b></li>
                        <li>Требуется предварительная
                            <?php
                            if ($exam_preparation->canRegister()) :
                                echo Html::a('регистрация', 'javascript: void(0)', ['data' => ['popup' => 'register', 'request' => Url::to(['exam-preparation/register', 'id' => $exam_preparation->id])]]);
                            else :
                                echo 'регистрация';
                            endif;
                            ?>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="dark_section">
            <div class="wrapper_section">
                <div class="title_section">Записаться</div>
                <div class="content_section_wrapper">
                    <div class="record_block_wrapper">
                        <div class="person flex">
                            <?php
                            /** @var User $person */
                            $person = ArrayHelper::getValue($exam_preparation, 'responsible');
                            ?>
                            <div class="image">
                                <a href="<?= $person->social; ?>">
                                    <?php
                                    $path = null;
                                    /** @var Files $file */
                                    if ($file = ArrayHelper::getValue($person, 'imageFile')) {
                                        $path = $file->makeResize(50, 50);
                                    }
                                    ?>
                                    <img src="<?= $path ?>" alt="">
                                </a>
                            </div>
                            <div class="name">
                                <p>
                                    <a href="<?= $person->social ?>"><?= $person->username ?></a>
                                </p>
                                <p><?= $person->position ?> </p>
                            </div>
                        </div>
                        <div class="phone"><a href="tel:+78007750679"> <i class="fa fa-phone"></i>+7 (800) 775-06-79</a>
                        </div>
                        <div class="email"><a href="mailto:study@mediasoft.team"> <i class="fa fa-envelope"></i>study@mediasoft.team</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

frontend/views/exam-preparation/register.php
<?php

use common\models\ExamPreparation;
use frontend\forms\CourseRegisterExamPreparation;
use yii\helpers\Html;
use yii\web\View;
use yii\widgets\Pjax;

/**
 * @var $this View
 * @var $register CourseRegisterExamPreparation
 * @var $send boolean
 * @var $exam_preparation ExamPreparation
 */

$icon = Html::tag('i', null, ['class' => ['fa', 'fa-times']]);
echo Html::a($icon, 'javascript: void(0);', ['class' => ['close_modal']]);
?>

<div class="wrapper_form">
    <?php
    Pjax::begin(['id' => 'register_form_pjax', 'enablePushState' => false]);
    echo Html::tag('h2', 'Регистрация на курс «' . $exam_preparation->sub_title . '»');
    if ($send === true) {
        echo $this->render('result', ['exam_preparation' => $exam_preparation]);
    } else {
        echo $this->render('blocks/_form', ['register' => $register]);
    }
    Pjax::end();
    ?>
</div>

frontend/views/exam-preparation/result.php
<?php

use common\models\ExamPreparation;
use frontend\forms\CourseRegisterExamPreparation;
use yii\web\View;

/**
 * @var $this View
 * @var $register CourseRegisterExamPreparation
 * @var $exam_preparation ExamPreparation
 */

?>

<div class="result">
    <h2>прошла успешно.</h2>
    <?php if ($exam_preparation->empty_date !== ExamPreparation::NOT_KNOW_DATE): ?>
        <?php if (date("Y-m-d h:i:s") < $exam_preparation->date_start): ?>
            <h2>Ждем вас <?php echo \Yii::$app->formatter->asDate($exam_preparation->date_start, 'long'); ?></h2>
        <?php else : ?>
            <h2>Ждем вас <?php echo $exam_preparation->getWeeklyExamPreparationForPage() . "."; ?></h2>
        <?php endif; ?>
    <?php endif; ?>
    <a href="javascript: void(0);" class="close_modal">Закрыть</a>
</div>