backend/controllers/StaffController.php
<?php

namespace backend\controllers;

use backend\forms\profile\SearchPersonal;
use services\profile\PersonalService;
use yii\base\Module;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\web\Response;

class StaffController extends Controller
{
    /** @var PersonalService */
    private $personal;

    public function __construct(string $id, Module $module, PersonalService $service, array $config = [])
    {
        $this->personal = $service;
        parent::__construct($id, $module, $config);
    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    ['allow' => true, 'roles' => ['@']]
                ],
            ],
        ];
    }

    public function actionList()
    {
        $filter = new SearchPersonal();
        $provider = $filter->search();

        return $this->render('list', [
            'provider' => $provider,
        ]);
    }

    public function actionUpdate(int $id)
    {
        $personal = $this->personal->find($id);
        if ($personal->load(\Yii::$app->request->post()) && $personal->validate()) {
            $this->personal->update($personal);
        }

        return $this->redirect(['staff/list']);
    }

    public function actionPreview(int $id)
    {
        $request = \Yii::$app->request;
        if ($request->getIsAjax() === false) {
            throw new BadRequestHttpException();
        }

        $personal = $this->personal->find($id);
        \Yii::$app->response->format = Response::FORMAT_JSON;
        return [
            'icon' => null,
            'title' => null,
            'sub_title' => null,
            'content' => $this->renderAjax('preview', ['personal' => $personal]),
        ];
    }
}

backend/views/staff/list.php
<?php

use backend\models\User;
use common\models\Files;
use yii\data\ActiveDataProvider;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\web\View;

/**
 * @var $this View
 * @var $provider ActiveDataProvider
 */

$this->title = 'Академия разработки Mediasoft: Персонал';
$this->params['links'][] = ['label' => 'Персонал', 'url' => null];

?>

<div class="row">
    <div class="col-lg-12">
        <div class="ibox">
            <div class="ibox-content">
                <h2>Список пользователей</h2>
                <?php
                echo GridView::widget([
                    'options' => ['class' => ['table-responsive']],
                    'layout' => '{items}',
                    'tableOptions' => ['class' => ['table', 'table-hover', 'issue-tracker']],
                    'dataProvider' => $provider,
                    'showHeader' => true,
                    'columns' => [
                        [
                            'attribute' => false,
                            'format' => 'raw',
                            'contentOptions' => ['style' => 'width: 10%; text-align: center;'],
                            'value' => function (User $record) {
                                $path = null;
                                /** @var Files $file */
                                if ($file = ArrayHelper::getValue($record, 'imageFile')) {
                                    $path = $file->makeResize(50, 50);
                                }
                                
                                return Html::img($path, ['style' => 'height: 50px;']);
                            }
                        ],
                        [
                            'attribute' => false,
                            'format' => 'raw',
                            'contentOptions' => ['class' => ['issue-info'], 'style' => 'width: 30%;'],
                            'value' => function (User $record) {
                                $render = Html::a(
                                    $record->username,
                                    ['staff/preview', 'id' => $record->id],
                                    ['class' => ['text-navy'], 'data' => ['show-modal' => 'myModal4']]
                                );
                                $render .= Html::tag('small', $record->position);
                                return $render;
                            }
                        ],
                        [
                            'attribute' => false,
                            'format' => 'raw',
                            'contentOptions' => ['style' => 'width: 30%;'],
                            'value' => function (User $record) {
                                return $record->email;
                            }
                        ],
                        [
                            'attribute' => false,
                            'format' => 'raw',
                            'contentOptions' => ['style' => 'width: 30%;'],
                            'value' => function (User $record) {
                                return Html::a($record->social, $record->social, [
                                    'class' => ['text-navy'],
                                    'target' => '_blank',
                                ]);
                            }
                        ],
                    ],
                ]);
                ?>
            </div>
        </div>
    </div>
</div>

backend/views/staff/preview.php
<?php

use backend\forms\profile\PersonalForm;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;
use yii\widgets\ActiveForm;

/**
 * @var $this View
 * @var $personal PersonalForm
 */


?>
<div class="ibox ">
    <div class="ibox-content">
        <?php

        $form = ActiveForm::begin(['action' => Url::to(['staff/update', 'id' => $personal->id])]);

        echo $form->field($personal, 'position')->textInput();
        echo $form->field($personal, 'social')->textInput();
        echo $form->field($personal, 'file')->fileInput();

        echo Html::beginTag('div', ['class' => ['actions', 'clearfix'] ]);
        echo Html::button('Закрыть', ['class' => ['btn', 'btn-white', 'pull-right'], 'data' => ['dismiss' => 'modal'], 'style' => 'margin: 0 5px;']);
        echo Html::submitButton('Сохранить изменения', ['class' => ['btn', 'btn-primary', 'pull-right']]);
        echo Html::endTag('div');

        ActiveForm::end();
        ?>
    </div>
</div>