common/models/Record.php
<?php

namespace common\models;

use Yii;
use yii\db\ActiveRecord;
use yii\db\Expression;
use yii\db\Query;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "{{%record}}".
 *
 * @property int $id
 * @property int $student_id
 * @property int $schedule_id
 * @property string $date_create
 * @property string $rating
 * @property int $listened
 * @property int $completed
 * @property int $accepted
 *
 * @property Schedule $schedule
 * @property Students $student
 */
class Record extends ActiveRecord
{

    const RESULT_POSITIVE = 1;
    const RESULT_NEGATIVE = 0;

    public static function tableName()
    {
        return '{{%record}}';
    }

    public function rules()
    {
        return [
            [['date_create'], 'filter', 'filter' => function ($value) {
                if (empty($value) === false) {
                    return (new \DateTime($value))->format('Y-m-d') . ' ' . (new \DateTime('now', new \DateTimeZone('Europe/Samara')))->format('H:i:s');
                }
                return null;
            }],
            [['listened', 'completed', 'accepted'], 'default', 'value' => static::RESULT_NEGATIVE],
            [['date_create'], 'default', 'value' => (new \DateTime('now', new \DateTimeZone('Europe/Samara')))->format('Y-m-d H:i:s')],
            [['student_id', 'schedule_id'], 'required'],
            [['student_id', 'schedule_id', 'listened', 'completed', 'accepted', 'rating'], 'integer'],
            [['date_create'], 'safe'],
            [
                ['student_id', 'schedule_id'],
                'unique',
                'targetAttribute' => ['student_id', 'schedule_id'],
                'message' => 'Данный стужент уже записан на данное направление'
            ],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'student_id' => 'Студент',
            'schedule_id' => 'Курс',
            'date_create' => 'Дата записи',
            'listened' => 'Прослушал',
            'completed' => 'Выполнил итоговое задание',
            'accepted' => 'Принят на стажировку',
        ];
    }

    public function getSchedule()
    {
        return $this->hasOne(Schedule::class, ['id' => 'schedule_id']);
    }

    public function getStudent()
    {
        return $this->hasOne(Students::class, ['id' => 'student_id']);
    }

    public function listTechnology()
    {
        $query = (new Query())
            ->select(['id', 'title'])
            ->from(Technology::tableName())
            ->orderBy(['title' => SORT_ASC]);

        return ArrayHelper::map($query->all(), 'id', 'title');
    }

    public function listSchedule()
    {
        $query = (new Query())
            ->select(['s.id', 's.date_start', 't.title'])
            ->from(['s' => Schedule::tableName()])
            ->innerJoin(['t' => Technology::tableName()], ['s.technology_id' => new Expression('t.id')])
            ->orderBy(['s.sorting' => SORT_ASC]);

        $records = $query->all();
        $result = [];
        foreach ($records as $record) {
            $result[$record['id']] = \Yii::t('app', '{title} ({date_start})', [
                'title' => $record['title'],
                'date_start' => \Yii::$app->formatter->asDate($record['date_start'], 'long'),
            ]);
        }

        return $result;
    }

    public function listStudents()
    {
        $query = (new Query())
            ->select(['id', 'name', 'email'])
            ->from(Students::tableName())
            ->orderBy(['email' => SORT_ASC]);

        $records = $query->all();
        $result = [];
        foreach ($records as $record) {
            $result[$record['id']] = \Yii::t('app', '{name} ({email})', [
                'name' => $record['name'],
                'email' => $record['email'],
            ]);
        }

        return $result;
    }

}

backend/controllers/RecordController.php
<?php

namespace backend\controllers;

use backend\forms\document\RecordDownload;
use backend\forms\record\CreateRecord;
use backend\forms\record\SearchRecord;
use backend\forms\student\CreateStudent;
use common\models\Record;
use common\models\Students;
use services\document\DocumentService;
use services\profile\StudentService;
use services\schedule\RecordService;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\web\Response;

/**
 * Site controller
 */
class RecordController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    ['allow' => true, 'roles' => ['@']]
                ],
            ],
        ];
    }

    public function actionCompare()
    {
        $request = \Yii::$app->request;
        if ($request->getIsAjax() === false) {
            throw new BadRequestHttpException();
        }

        $student = new CreateStudent();
        $student->load(\Yii::$app->request->post());

        $record = Students::find()
            ->where(['=', 'email', $student->email])
            ->one();

        \Yii::$app->response->format = Response::FORMAT_JSON;
        if ($record !== null) {
            return [
                'compare' => true,
                'content' => $this->renderAjax('compare', ['student' => $student, 'record' => $record])
            ];
        }
        return [
            'compare' => false,
            'content' => null
        ];

    }

    public function actionList()
    {
        $request = \Yii::$app->request;
        $student_form = new CreateStudent();

        if ($student_form->load($request->post()) && $student_form->validate()) {
            (new StudentService())->insert($student_form);
            \Yii::$app->session->setFlash('success', 'Новый студент был успешно создан');
            return $this->redirect(['record/list']);
        }

        $record_form = new CreateRecord();
        if ($record_form->load($request->post()) && $record_form->validate()) {
            (new RecordService())->create($record_form);
            \Yii::$app->session->setFlash('success', 'Новая запись на курс была успешно создана');
            return $this->redirect(['record/list']);
        }

        $record_filter = new SearchRecord();
        $record_provider = $record_filter->search();

        return $this->render('list', [
            'record_form' => $record_form,
            'student_form' => $student_form,
            'record_filter' => $record_filter,
            'record_provider' => $record_provider,
        ]);
    }

    public function actionChangeListened(int $id)
    {
        $request = \Yii::$app->request;
        if ($request->getIsAjax() === false) {
            throw new BadRequestHttpException();
        }

        $result = $request->post('checked') === 'true' ? Record::RESULT_POSITIVE : Record::RESULT_NEGATIVE;
        (new RecordService())->listened($id, $result);
    }

    public function actionChangeCompleted(int $id)
    {
        $request = \Yii::$app->request;
        if ($request->getIsAjax() === false) {
            throw new BadRequestHttpException();
        }

        $result = $request->post('checked') === 'true' ? Record::RESULT_POSITIVE : Record::RESULT_NEGATIVE;
        (new RecordService())->completed($id, $result);
    }

    public function actionChangeAccepted(int $id)
    {
        $request = \Yii::$app->request;
        if ($request->getIsAjax() === false) {
            throw new BadRequestHttpException();
        }

        $result = $request->post('checked') === 'true' ? Record::RESULT_POSITIVE : Record::RESULT_NEGATIVE;
        (new RecordService())->accepted($id, $result);
    }

    public function actionDownload()
    {
        $download = new RecordDownload();
        DocumentService::instance()
            ->setFilename($download->getFileName())
            ->generate($download->search());
    }

}

backend/views/record/blocks/_filter.php
<?php

use backend\forms\record\SearchRecord;
use yii\helpers\Html;
use yii\web\View;
use yii\widgets\ActiveForm;

/**
 * @var $this View
 * @var $filter SearchRecord
 */

$form = ActiveForm::begin(['enableClientValidation' => false, 'method' => 'get', 'action' => ['record/list']]);

?>
    <div class="row">
        <div class="col-lg-6">
            <?php
            echo $form->field($filter, 'technology')->dropDownList($filter->listTechnology(), [
                'class' => ['select2', 'form-group', 'change_submit'],
                'prompt' => '- Выберите направление -',
            ]);
            ?>
        </div>
        <div class="col-lg-6">
            <?php
            if (empty($filter->technology) === false) {
                echo $form->field($filter, 'schedule_id')->dropDownList($filter->listSchedule(), [
                    'class' => ['select2'],
                    'prompt' => '- Выберите курс -',
                ]);
            }
            ?>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <?= $form->field($filter, 'name')->textInput([
                'placeholder' => $filter->getAttributeLabel('name'),
                'autocomplete' => 'off',
            ])->label(false); ?>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <?php
            echo $form->field($filter, 'listened')->checkbox(['class' => ['iCheck']]);
            echo $form->field($filter, 'completed')->checkbox(['class' => ['iCheck']]);
            ?>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <?= Html::submitInput('Применить фильтр', ['class' => ['btn', 'btn-primary', 'pull-right']]); ?>
        </div>
    </div>
<?php

ActiveForm::end();

backend/views/record/blocks/_list_student.php
<?php

use backend\forms\record\SearchRecord;
use common\models\Record;
use yii\data\ActiveDataProvider;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\web\View;

/**
 * @var $this View
 * @var $provider ActiveDataProvider
 * @var $filter SearchRecord
 */

echo GridView::widget([
    'dataProvider' => $provider,
    'options' => ['class' => ['table-responsive']],
    'layout' => "{items}\n{pager}",
    'tableOptions' => ['class' => ['table', 'table-striped', 'table-hover']],
    'columns' => [
        [
            'attribute' => false,
            'format' => 'raw',
            'contentOptions' => ['style' => 'width: 15%'],
            'value' => function (Record $record) {
                $date_begin = \Yii::$app->formatter->asDate(ArrayHelper::getValue($record, 'schedule.date_start'), 'long');
                return \Yii::t('app', '{title} <br> <small>({date})</small>', [
                    'title' => ArrayHelper::getValue($record, 'schedule.technology.title'),
                    'date' => $date_begin,
                ]);
            }
        ],
        [
            'attribute' => false,
            'format' => 'raw',
            'contentOptions' => ['style' => 'width: 15%'],
            'value'          => function (Record $record) {
                $date_create_record = new DateTime($record->date_create);
                if ($date_create_record->format('H:i:s') === "00:00:00"
                    && $date_create_record->format('Y-m-d') < (new DateTime('2019-12-01'))->format('Y-m-d')) {
                    return \Yii::$app->formatter->asDate($record->date_create, 'long');
                }
                return \Yii::$app->formatter->asDate($record->date_create, 'long') . " "
                    . \Yii::$app->formatter->asTime($record->date_create, 'short');
            }
        ],
        [
            'attribute' => false,
            'format' => 'raw',
            'contentOptions' => ['style' => 'width: 15%'],
            'value' => function (Record $record) {
                $name = ArrayHelper::getValue($record, 'student.name');
                if (empty($name) === true) {
                    $name = 'Не указано';
                }

                $render = Html::a($name, ['students/preview', 'id' => ArrayHelper::getValue($record, 'student.id')], [
                    'class' => ['text-navy'],
                    'data' => ['show-modal' => 'myModal4']
                ]);
                return $render;
            }
        ],
        [
            'attribute' => false,
            'format' => 'raw',
            'contentOptions' => ['style' => 'width: 15%'],
            'value' => function (Record $record) {
                return ArrayHelper::getValue($record, 'student.email');
            }
        ],
        [
            'attribute' => false,
            'format' => 'raw',
            'contentOptions' => ['style' => 'width: 15%'],
            'value' => function (Record $record) {
                return ArrayHelper::getValue($record, 'student.social');
            }
        ],
        [
            'attribute' => false,
            'format' => 'raw',
            'contentOptions' => ['style' => 'width: 25%'],
            'value' => function (Record $record) {
                return ArrayHelper::getValue($record, 'student.abilities');
            }
        ],
    ],
]);

backend/views/record/blocks/_record.php
<?php

use yii\helpers\Html;
use yii\web\View;
use yii\widgets\ActiveForm;

/**
 * @var $this View
 * @var $record \backend\forms\record\CreateRecord
 */


$form = ActiveForm::begin();

echo $form->field($record, 'student_id')->dropDownList($record->listStudents(), [
    'class' => ['select2'],
    'prompt' => 'Выберите студента',
]);

echo $form->field($record, 'schedule_id')->dropDownList($record->listSchedule(), [
    'class' => ['select2'],
    'prompt' => 'Выберите курс'
]);

$config = [
    'template' => "
{label}\n
 <div class=\"input-group\">
 <span class=\"input-group-addon\">
 <i class=\"fa fa-calendar\"></i>
 </span> 
 {input}\n{hint}\n{error} 
 </div>",
];
echo $form->field($record, 'date_create', $config)->textInput([
    'class' => ['datepiker', 'form-control'],
    'autocomplete' => 'off',
]);

echo Html::beginTag('div', ['class' => ['form-group', 'text-right']]);
echo Html::submitInput('Записать на курс', ['class' => ['btn', 'btn-primary']]);
echo Html::endTag('div');

ActiveForm::end();

backend/views/record/blocks/_student.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;
use yii\widgets\ActiveForm;

/**
 * @var $this View
 * @var $student \backend\forms\student\CreateStudent
 */

$form = ActiveForm::begin(['options' => [
    'data' => ['compare' => Url::to(['record/compare'])]
]]);
echo $form->field($student, 'name')->textInput(['autocomplete' => 'off',]);
echo $form->field($student, 'email')->textInput(['autocomplete' => 'off',]);
echo $form->field($student, 'social')->textInput(['autocomplete' => 'off',]);
echo $form->field($student, 'abilities')->textarea(['rows' => 4]);

echo Html::beginTag('div', ['class' => ['form-group', 'text-right']]);
echo Html::submitInput('Создать студента', ['class' => ['btn', 'btn-primary', 'check_compare']]);
echo Html::endTag('div');

ActiveForm::end();